### ISSUE TITLE
Inconsistent comment inside the code

### ISSUE THREAD

**Issue by diogorolo** [revolucaodosbytes/ahoy-api#2]
In https://github.com/revolucaodosbytes/ahoy-api/blob/91682e957d61848db04417d2d69f344375c45815/app/Http/Controllers/Auth/AuthController.php#L87 , the comment is inconsistent.

Maybe just remove the comments, since the code is self explanatory?

```
// Rate limit to 1 requests per minute
$throttler = Throttle::get($request, 5, 1);
```

**Comment by vaurdan** [comment]
Thanks for your help @diogorolo!
